### DISCUSSION TITLE
Reference server config

### DISCUSSION THREAD

**Discussion by jfolz** [devpi/devpi#885] [Q&A] [answered]
Hi,

I'm looking into setting up a caching PyPI mirror for internal use. `devpi-gen-config` seems to be a good starting point, but it prints this warning:
```
$ devpi-gen-config
It is highly recommended to use a configuration file for devpi-server, see --configfile option.
...
```

So far the best reference as to what a configfile could look like I found [here](https://devpi.net/docs/devpi/devpi/stable/+doc/quickstart-server.html#using-a-configuration-file-for-devpi-server):

```
devpi-server:
  serverdir: /var/db/devpi-server
  secretfile: /etc/devpi-server/secret
  host: localhost
  port: 8080
```

That doesn't look complete. At least `devpi-server --help` is a lot more verbose. Is there a more complete reference config I can refer to?
