### ISSUE TITLE
Question for accessing devpi-web in docker

### ISSUE THREAD

**Issue by zhangsimingshannonai** [devpi/devpi#668]
Hello,I'm using devpi in docker and my docker is installed in Ubuntu 16.04 LTS.

First,I know after installed the plugin devpi-web,I need to add "host 0.0.0.0" to start the devpi-server,so that another computer in the local-network can access the web for my devpi-server.

It's OK.But this time I installed devpi-server in a docker,and I still add "host 0.0.0.0" to start my devpi-server ,I can access the devpi-server on my Ubuntu(docker's host) ,but I cannot access the web via another computer in the local-network.This indeed confused me .
Can you help me out? Sincerely hope your reply.

**Comment by zhangsimingshannonai** [comment]
Here's my docker-compose.yaml
```
root@ip-172-31-25-120:/devpi/docker-devpi# cat docker-compose.yml 
version: '2'
services: 
    devpi: 
       image: devpi
       container_name: devpi
       network_mode: host
       volumes:
           - ./data:/data
       ports:
           - 3141:3141
       env_file: .env
       restart: always
```
