### ISSUE TITLE
Question for devpi-ldap connection

### ISSUE THREAD

**Issue by zhangsimingshannonai** [devpi/devpi#676]
Hi, I'm using devpi and I'm trying to use devpi-ldap plugin.
My OS is Ubuntu16.04LTS, and of course, I have a functional ldap server.

My devpi version is:
DEVPI_SERVER_VERSION=4.9.0
DEVPI_WEB_VERSION=3.5.1
DEVPI_CLIENT_VERSION=4.4.0
DEVPI_LDAP_VERSION=1.2.2

The follow is my operation:

1. Install a devpi-server, add devpi-ldap plugin.

2. use
```
devpi-server --ldap-config /ldap/ldap.yaml --serverdir /data/server --host 0.0.0.0 --port 3141 --start --init
```
to start a new devpi-server with ldap.

3. do a user login authentication,but it occured:
```
root@ip-172-31-28-20:/data# devpi login Tom
password for user Tom: 
WARN: devpi-client-4.4.0 got an unversioned reply, assuming API-VERSION 2 (as implemented by devpi-server-2.0)
POST http://localhost:3141/+login
500 Internal Server Error: Internal Server Error

The server encountered an unexpected internal server error

(generated by waitress)
```

Is this something wrong with the version of devpi-ldap? Or which step I did is wrong?
Please help me figure it out, thanks a lot!

By the way, here's the yaml of ldap:
```
zhangsiming@ip-172-31-28-20:~/docker-devpi$ cat ldap/ldap.yaml 
---
  devpi-ldap:
    url: ldaps://ldap.xxxxxxxxx.com
    user_search:
        base: ou=users,dc=xxxxxxxx,dc=com 
        filter: (objectClass=person)(memberOf=cn=devpi,ou=project,dc=xxxxxxxxx,dc=com)
        attribute_name: uid
        scope: whole-subtree
        userdn: cn=devpi,ou=project,dc=xxxxxxxx,dc=com
        password: h6xnoI^3
    group_search:
        base: ou=department,dc=xxxxxxxx,dc=com
        filter: (objectclass=groupOfUniqueNames)
        attribute_name: cn
        scope: whole-subtree
```
